name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
  
      - name: Activate venv and install deps
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -r pyproject.toml --extra dev

      - name: Lint with ruff
        run: |
          make lint

      - name: Type check with mypy
        run: |
          make typecheck

      - name: Test with pytest
        run: |
          make coverage